class CreateRecipesV3 < ActiveRecord::Migration[5.1]
  def change
    create_table :recipes do |t|
      t.string :name, default: ""
      t.float :cholesterol, default: 0.0
      t.string :cholesterol_unit, default: ""
      t.float :calorie, default: 0.0
      t.string :calorie_unit, default: ""
      t.float :protein, default: 0.0
      t.string :protein_unit, default: ""
      t.float :carbohydrate, default: 0.0
      t.string :carbohydrate_unit, default: ""
      t.float :fiber, default: 0.0
      t.string :fiber_unit, default: ""
      t.float :sugar, default: 0.0
      t.string :sugar_unit, default: ""
      t.float :fat_total, default: 0.0
      t.string :fat_total_unit, default: ""
      t.float :fat_saturated, default: 0.0
      t.string :fat_saturated_unit, default: ""
      t.float :calcium, default: 0.0
      t.string :calcium_unit, default: ""
      t.float :iron, default: 0.0
      t.string :iron_unit, default: ""
      t.float :magnesium, default: 0.0
      t.string :magnesium_unit, default: ""
      t.float :phosphorus, default: 0.0
      t.string :phosphorus_unit, default: ""
      t.float :potassium, default: 0.0
      t.string :potassium_unit, default: ""
      t.float :sodium, default: 0.0
      t.string :sodium_unit, default: ""
      t.float :zinc, default: 0.0
      t.string :zinc_unit, default: ""
      t.float :copper, default: 0.0
      t.string :copper_unit, defualt: ""
      t.float :manganese, default: 0.0
      t.string :manganese_unit, default: ""
      t.float :selenium, default: 0.0
      t.string :selenium_unit, default: ""
      t.float :vitamin_a, default: 0.0
      t.string :vitamin_a_unit, default: ""
      t.float :vitamin_e, default: 0.0
      t.string :vitamin_e_unit, default: ""
      t.float :vitamin_c, default: 0.0
      t.string :vitamin_c_unit, default: ""
      t.float :thiamin, default: 0.0
      t.string :thiamin_unit, default: ""
      t.float :riboflavin, default: 0.0
      t.string :riboflavin_unit, default: ""
      t.float :niacin, default: 0.0
      t.string :niacin_unit, default: ""
      t.float :vitamin_b6, default: 0.0
      t.string :vitamin_b6_unit, default: ""
      t.float :vitamin_b12, default: 0.0
      t.string :vitamin_b12_unit, default: ""
      t.float :choline, default: 0.0
      t.string :choline_unit, default: ""
      t.float :vitamin_k, default: 0.0
      t.string :vitamin_k_unit, default: ""
      t.float :folate, default: 0.0
      t.string :folate_unit, default: ""
      t.timestamps
    end
  end
end
