class AddIngredientsV2 < ActiveRecord::Migration[5.1]
  def change
    create_table :ingredients do |t|
      t.string :name, default: ""
      t.string :ndbno, default: ""
      t.string :upc, default: ""
      t.float :density, default: 0.0
      t.string :usda_unit, default: ""
      t.float :cholesterol_per_usda_unit, default: 0.0
      t.string :cholesterol_unit, default: ""
      t.float :calorie_per_usda_unit, default: 0.0
      t.string :calorie_unit, default: ""
      t.float :protein_per_usda_unit, default: 0.0
      t.string :protein_unit, default: ""
      t.float :carbohydrate_per_usda_unit, default: 0.0
      t.string :carbohydrate_unit, default: ""
      t.float :fiber_per_usda_unit, default: 0.0
      t.string :fiber_unit, default: ""
      t.float :sugar_per_usda_unit, default: 0.0
      t.string :sugar_unit, default: ""
      t.float :fat_total_per_usda_unit, default: 0.0
      t.string :fat_total_unit, default: ""
      t.float :fat_saturated_per_usda_unit, default: 0.0
      t.string :fat_saturated_unit, default: ""
      t.float :calcium_per_usda_unit, default: 0.0
      t.string :calcium_unit, default: ""
      t.float :iron_per_usda_unit, default: 0.0
      t.string :iron_unit, default: ""
      t.float :magnesium_per_usda_unit, default: 0.0
      t.string :magnesium_unit, default: ""
      t.float :phosphorus_per_usda_unit, default: 0.0
      t.string :phosphorus_unit, default: ""
      t.float :potassium_per_usda_unit, default: 0.0
      t.string :potassium_unit, default: ""
      t.float :sodium_per_usda_unit, default: 0.0
      t.string :sodium_unit, default: ""
      t.float :zinc_per_usda_unit, default: 0.0
      t.string :zinc_unit, default: ""
      t.float :copper_per_usda_unit, default: 0.0
      t.string :copper_unit, defualt: ""
      t.float :manganese_per_usda_unit, default: 0.0
      t.string :manganese_unit, default: ""
      t.float :selenium_per_usda_unit, default: 0.0
      t.string :selenium_unit, default: ""
      t.float :vitamin_a_per_usda_unit, default: 0.0
      t.string :vitamin_a_unit, default: ""
      t.float :vitamin_e_per_usda_unit, default: 0.0
      t.string :vitamin_e_unit, default: ""
      t.float :vitamin_c_per_usda_unit, default: 0.0
      t.string :vitamin_c_unit, default: ""
      t.float :thiamin_per_usda_unit, default: 0.0
      t.string :thiamin_unit, default: ""
      t.float :riboflavin_per_usda_unit, default: 0.0
      t.string :riboflavin_unit, default: ""
      t.float :niacin_per_usda_unit, default: 0.0
      t.string :niacin_unit, default: ""
      t.float :vitamin_b6_per_usda_unit, default: 0.0
      t.string :vitamin_b6_unit, default: ""
      t.float :vitamin_b12_per_usda_unit, default: 0.0
      t.string :vitamin_b12_unit, default: ""
      t.float :choline_per_usda_unit, default: 0.0
      t.string :choline_unit, default: ""
      t.float :vitamin_k_per_usda_unit, default: 0.0
      t.string :vitamin_k_unit, default: ""
      t.float :folate_per_usda_unit, default: 0.0
      t.string :folate_unit, default: ""
      t.timestamps
    end
  end
end
